// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type CreateOrderInput struct {
	ID    string  `json:"id"`
	Price float64 `json:"price"`
	Tax   float64 `json:"tax"`
}

type Mutation struct {
}

type Query struct {
}
