# REST API

### Criar um pedido
POST http://localhost:8000/order
Content-Type: application/json

{
    "id": "123",
    "price": 100.0,
    "tax": 10.0
}

### Listar pedidos
GET http://localhost:8000/order

# gRPC

### Criar um pedido (usando grpcurl)
# grpcurl -d '{"id": "123", "price": 100.0, "tax": 10.0}' -plaintext localhost:50051 pb.OrderService/CreateOrder

### Listar pedidos (usando grpcurl)
# grpcurl -plaintext localhost:50051 pb.OrderService/ListOrders

# GraphQL

### Criar um pedido
POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "mutation ($input: CreateOrderInput!) { createOrder(input: $input) { id price tax finalPrice } }",
    "variables": {
        "input": {
            "id": "123",
            "price": 100.0,
            "tax": 10.0
        }
    }
}

### Listar pedidos
POST http://localhost:8080/query
Content-Type: application/json

{
    "query": "query { orders { id price tax finalPrice } }"
} 